Updated ort to 2.0.0
Anush008/fastembed-rs pull request #12
Opened 2024-01-07 11:38 UTC by joshniemela

Migrated the code to ort to 2.0.0 based on the breaking API changes

2024-01-07 11:49 UTC, Anush008 commented
Maybe we can dynamic linking mentioned here.
https://ort.pyke.io/setup/linking#load-dynamic-a-glimmer-of-hope

From FastEmbed-go https://github.com/Anush008/fastembed-go/blob/7fe735ed91f0d510ce07b58c6d5dd5ae31fb0218/.github/workflows/release.yml#L30-L34
for `ORT_DYLIB_PATH`.

2024-01-08 18:10 UTC, decahedron1 requested changes

2024-01-08 18:10 UTC, decahedron1 commented on Cargo.toml
> +ort = { version = "2.0.0-alpha.4", features = ["load-dynamic"] }
Libraries should only enable features they need.

```toml
[dependencies]
ort = { version = "2.0.0-alpha.4", default-features = false, features = [ "ndarray" ] }

[dev-dependencies]
ort = "2.0.0-alpha.4"
```

2024-01-08 18:22 UTC, decahedron1 commented
@Anush008 btw, https://github.com/Anush008/fastembed-rs/pull/12/commits/7e0526a1b8b27c9856ce9e8a1fb521301f9a77d0 has a critical performance fix. @joshniemela and I found that `PaddingStrategy::Fixed` caused `fastembed-rs` to be almost 15x slower than a Python equivalent on shorter sequences. Like the comment says, a new field should be added to `InitOptions` to change the padding strategy if the user wishes (it should also be marked [`#[non_exhaustive]`](https://doc.rust-lang.org/reference/attributes/type_system.html) imo).

2024-01-08 18:38 UTC, decahedron1 commented
Indeed it significantly improves #9.

`master`
```
init: 138.47ms
passage_embed: 579.84ms
query_embed: 147.26ms
```
`v2`
```
init: 133.73ms
passage_embed: 39.97ms
query_embed: 4.50ms
```

2024-01-08 18:42 UTC, joshniemela commented
> Indeed it significantly improves #9.
> 
> `master`
> 
> ```
> init: 138.47ms
> passage_embed: 579.84ms
> query_embed: 147.26ms
> ```
> 
> `v2`
> 
> ```
> init: 133.73ms
> passage_embed: 39.97ms
> query_embed: 4.50ms
> ```

Is it possible to do a test on python as well on the same machine?

2024-01-08 18:42 UTC, merged

2024-01-08 18:45 UTC, decahedron1 commented
> Is it possible to do a test on python as well on the same machine?

```
init: 118.33ms
passage_embed: 17.55ms
query_embed: 3.51ms
```

2024-01-08 18:50 UTC, Anush008 commented
Bummer. Should've been a major release.

2024-01-08 18:51 UTC, Anush008 commented
@joshniemela, @decahedron1 Thanks for the efforts. Super grateful. This is amazing.

2024-01-08 19:17 UTC, Anush008 commented
After some commit slogging, it is finally up.
https://github.com/Anush008/fastembed-rs/releases/tag/v2.0.0

I've yanked `1.11.0`.

2024-01-10 22:21 UTC, prattcmp commented
Thank you for the perf enhancements, but the ONNX runtime upgrade needs to be notated.

This should be released as v2.0.0-alpha or with some other indication that it is not a stable release since it depends on an alpha version of ONNX runtime.

2024-01-10 23:35 UTC, decahedron1 commented
> This should be released as v2.0.0-alpha or with some other indication that it is not a stable release since it depends on an alpha version of ONNX runtime.

ort v2.0.0-alpha.4 uses ONNX Runtime v1.16.3, so only a minor upgrade as ort 1.16 uses 1.16.0. It does not use an alpha version of ONNX Runtime.

2024-01-12 17:07 UTC, prattcmp commented
> > This should be released as v2.0.0-alpha or with some other indication that it is not a stable release since it depends on an alpha version of ONNX runtime.
> 
> ort v2.0.0-alpha.4 uses ONNX Runtime v1.16.3, so only a minor upgrade as ort 1.16 uses 1.16.0. It does not use an alpha version of ONNX Runtime.

Thank you for correcting that the _crate_ is alpha, not the actual runtime. Nevertheless, this release is not stable and should indicate that it is using an alpha version of a crate.